sudo: required
services:
  - docker

before_install:
  - docker build -t codeshifu/react-docker -f Dockerfile.dev .

script:
  - docker run codeshifu/react-docker npm run test -- --coverage --watchAll=false
